##
##  Copyright (c) 1999-2004,2008-2015 Apple Inc. All Rights Reserved.
##
##  @APPLE_LICENSE_HEADER_START@
##
##  This file contains Original Code and/or Modifications of Original Code
##  as defined in and that are subject to the Apple Public Source License
##  Version 2.0 (the 'License'). You may not use this file except in
##  compliance with the License. Please obtain a copy of the License at
##  http://www.opensource.apple.com/apsl/ and read it before using this
##  file.
##
##  The Original Code and all software distributed under the License are
##  distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
##  EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
##  INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
##  FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
##  Please see the License for the specific language governing rights and
##  limitations under the License.
##
##  @APPLE_LICENSE_HEADER_END@
##
##  oidsalg.h -- OIDs defining crypto algorithms
##

var
  CSSMOID_MD2*: SecAsn1Oid
  CSSMOID_MD4*: SecAsn1Oid
  CSSMOID_MD5*: SecAsn1Oid
  CSSMOID_RSA*: SecAsn1Oid
  CSSMOID_MD2WithRSA*: SecAsn1Oid
  CSSMOID_MD4WithRSA*: SecAsn1Oid
  CSSMOID_MD5WithRSA*: SecAsn1Oid
  CSSMOID_SHA1WithRSA*: SecAsn1Oid
  CSSMOID_SHA224WithRSA*: SecAsn1Oid
  CSSMOID_SHA256WithRSA*: SecAsn1Oid
  CSSMOID_SHA384WithRSA*: SecAsn1Oid
  CSSMOID_SHA512WithRSA*: SecAsn1Oid
  CSSMOID_SHA1WithRSA_OIW*: SecAsn1Oid
  CSSMOID_RSAWithOAEP*: SecAsn1Oid
  CSSMOID_OAEP_MGF1*: SecAsn1Oid
  CSSMOID_OAEP_ID_PSPECIFIED*: SecAsn1Oid
  CSSMOID_DES_CBC*: SecAsn1Oid
  CSSMOID_ANSI_DH_PUB_NUMBER*: SecAsn1Oid
  CSSMOID_ANSI_DH_STATIC*: SecAsn1Oid
  CSSMOID_ANSI_DH_ONE_FLOW*: SecAsn1Oid
  CSSMOID_ANSI_DH_EPHEM*: SecAsn1Oid
  CSSMOID_ANSI_DH_HYBRID1*: SecAsn1Oid
  CSSMOID_ANSI_DH_HYBRID2*: SecAsn1Oid
  CSSMOID_ANSI_DH_HYBRID_ONEFLOW*: SecAsn1Oid
  CSSMOID_ANSI_MQV1*: SecAsn1Oid
  CSSMOID_ANSI_MQV2*: SecAsn1Oid
  CSSMOID_ANSI_DH_STATIC_SHA1*: SecAsn1Oid
  CSSMOID_ANSI_DH_ONE_FLOW_SHA1*: SecAsn1Oid
  CSSMOID_ANSI_DH_EPHEM_SHA1*: SecAsn1Oid
  CSSMOID_ANSI_DH_HYBRID1_SHA1*: SecAsn1Oid
  CSSMOID_ANSI_DH_HYBRID2_SHA1*: SecAsn1Oid
  CSSMOID_ANSI_MQV1_SHA1*: SecAsn1Oid
  CSSMOID_ANSI_MQV2_SHA1*: SecAsn1Oid
  CSSMOID_PKCS3*: SecAsn1Oid
  CSSMOID_DH*: SecAsn1Oid
  CSSMOID_DSA*: SecAsn1Oid     ##  BSAFE only
  CSSMOID_DSA_CMS*: SecAsn1Oid ##  X509/CMS
  CSSMOID_DSA_JDK*: SecAsn1Oid ##  JDK 1.1
  CSSMOID_SHA1WithDSA*: SecAsn1Oid ##  BSAFE
  CSSMOID_SHA1WithDSA_CMS*: SecAsn1Oid ##  X509/CMS
  CSSMOID_SHA1WithDSA_JDK*: SecAsn1Oid ##  JDK 1.1
  CSSMOID_SHA1*: SecAsn1Oid
  CSSMOID_SHA224*: SecAsn1Oid
  CSSMOID_SHA256*: SecAsn1Oid
  CSSMOID_SHA384*: SecAsn1Oid
  CSSMOID_SHA512*: SecAsn1Oid
  CSSMOID_ecPublicKey*: SecAsn1Oid
  CSSMOID_ECDSA_WithSHA1*: SecAsn1Oid
  CSSMOID_ECDSA_WithSHA224*: SecAsn1Oid
  CSSMOID_ECDSA_WithSHA256*: SecAsn1Oid
  CSSMOID_ECDSA_WithSHA384*: SecAsn1Oid
  CSSMOID_ECDSA_WithSHA512*: SecAsn1Oid
  CSSMOID_ECDSA_WithSpecified*: SecAsn1Oid
  CSSMOID_APPLE_ISIGN*: SecAsn1Oid
  CSSMOID_APPLE_X509_BASIC*: SecAsn1Oid
  CSSMOID_APPLE_TP_SSL*: SecAsn1Oid
  CSSMOID_APPLE_TP_LOCAL_CERT_GEN*: SecAsn1Oid
  CSSMOID_APPLE_TP_CSR_GEN*: SecAsn1Oid
  CSSMOID_APPLE_TP_REVOCATION_CRL*: SecAsn1Oid
  CSSMOID_APPLE_TP_REVOCATION_OCSP*: SecAsn1Oid
  CSSMOID_APPLE_TP_SMIME*: SecAsn1Oid
  CSSMOID_APPLE_TP_EAP*: SecAsn1Oid
  CSSMOID_APPLE_TP_CODE_SIGN*: SecAsn1Oid
  CSSMOID_APPLE_TP_SW_UPDATE_SIGNING*: SecAsn1Oid
  CSSMOID_APPLE_TP_IP_SEC*: SecAsn1Oid
  CSSMOID_APPLE_TP_ICHAT*: SecAsn1Oid
  CSSMOID_APPLE_TP_RESOURCE_SIGN*: SecAsn1Oid
  CSSMOID_APPLE_TP_PKINIT_CLIENT*: SecAsn1Oid
  CSSMOID_APPLE_TP_PKINIT_SERVER*: SecAsn1Oid
  CSSMOID_APPLE_TP_CODE_SIGNING*: SecAsn1Oid
  CSSMOID_APPLE_TP_PACKAGE_SIGNING*: SecAsn1Oid
  CSSMOID_APPLE_TP_MACAPPSTORE_RECEIPT*: SecAsn1Oid
  CSSMOID_APPLE_TP_APPLEID_SHARING*: SecAsn1Oid
  CSSMOID_APPLE_TP_TIMESTAMPING*: SecAsn1Oid
  CSSMOID_APPLE_TP_REVOCATION*: SecAsn1Oid
  CSSMOID_APPLE_TP_PASSBOOK_SIGNING*: SecAsn1Oid
  CSSMOID_APPLE_TP_MOBILE_STORE*: SecAsn1Oid
  CSSMOID_APPLE_TP_ESCROW_SERVICE*: SecAsn1Oid
  CSSMOID_APPLE_TP_PROFILE_SIGNING*: SecAsn1Oid
  CSSMOID_APPLE_TP_QA_PROFILE_SIGNING*: SecAsn1Oid
  CSSMOID_APPLE_TP_TEST_MOBILE_STORE*: SecAsn1Oid
  CSSMOID_APPLE_TP_PCS_ESCROW_SERVICE*: SecAsn1Oid
  CSSMOID_APPLE_TP_PROVISIONING_PROFILE_SIGNING*: SecAsn1Oid
  CSSMOID_APPLE_FEE*: SecAsn1Oid
  CSSMOID_APPLE_ASC*: SecAsn1Oid
  CSSMOID_APPLE_FEE_MD5*: SecAsn1Oid
  CSSMOID_APPLE_FEE_SHA1*: SecAsn1Oid
  CSSMOID_APPLE_FEED*: SecAsn1Oid
  CSSMOID_APPLE_FEEDEXP*: SecAsn1Oid
  CSSMOID_APPLE_ECDSA*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_IDENTITY*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_EMAIL_SIGN*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_EMAIL_ENCRYPT*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_ARCHIVE_LIST*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_ARCHIVE_STORE*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_ARCHIVE_FETCH*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_ARCHIVE_REMOVE*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_SHARED_SERVICES*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_VALUE_USERNAME*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_VALUE_PASSWORD*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_VALUE_HOSTNAME*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_VALUE_RENEW*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_VALUE_ASYNC*: SecAsn1Oid
  CSSMOID_DOTMAC_CERT_REQ_VALUE_IS_PENDING*: SecAsn1Oid
  CSSMOID_PKCS5_DIGEST_ALG*: SecAsn1Oid
  CSSMOID_PKCS5_ENCRYPT_ALG*: SecAsn1Oid
  CSSMOID_PKCS5_HMAC_SHA1*: SecAsn1Oid
  CSSMOID_PKCS5_pbeWithMD2AndDES*: SecAsn1Oid
  CSSMOID_PKCS5_pbeWithMD2AndRC2*: SecAsn1Oid
  CSSMOID_PKCS5_pbeWithMD5AndDES*: SecAsn1Oid
  CSSMOID_PKCS5_pbeWithMD5AndRC2*: SecAsn1Oid
  CSSMOID_PKCS5_pbeWithSHA1AndDES*: SecAsn1Oid
  CSSMOID_PKCS5_pbeWithSHA1AndRC2*: SecAsn1Oid
  CSSMOID_PKCS5_PBKDF2*: SecAsn1Oid
  CSSMOID_PKCS5_PBES2*: SecAsn1Oid
  CSSMOID_PKCS5_PBMAC1*: SecAsn1Oid
  CSSMOID_PKCS5_RC2_CBC*: SecAsn1Oid
  CSSMOID_PKCS5_DES_EDE3_CBC*: SecAsn1Oid
  CSSMOID_PKCS5_RC5_CBC*: SecAsn1Oid
  CSSMOID_PKCS12_pbeWithSHAAnd128BitRC4*: SecAsn1Oid
  CSSMOID_PKCS12_pbeWithSHAAnd40BitRC4*: SecAsn1Oid
  CSSMOID_PKCS12_pbeWithSHAAnd3Key3DESCBC*: SecAsn1Oid
  CSSMOID_PKCS12_pbeWithSHAAnd2Key3DESCBC*: SecAsn1Oid
  CSSMOID_PKCS12_pbeWithSHAAnd128BitRC2CBC*: SecAsn1Oid
  CSSMOID_PKCS12_pbewithSHAAnd40BitRC2CBC*: SecAsn1Oid
